### ISSUE TITLE
Make it possible to select a price range for the skin

### ISSUE THREAD

**Issue by kudaevE** [sotolko/csgo-market-sniper#1]
It would be very convenient if you could also specify a price range for any skins. I hope the Author will answer my request), and the program itself is written very convenient.

**Comment by sotolko** [comment]
Hi, I will implement that in few days.

**Comment by kudaevE** [comment]
You can also add to buy with a streak of stickers, and not certain ones. Good idea I think

**Comment by sotolko** [comment]
Do you mean that you can choose which stickers you want to be on skin? Or you mean to choose number of stickers on skin

**Comment by kudaevE** [comment]
The number of stickers, let's say 4 stickers for AK-47, any, but you set
the price for the purchase of the order

ср, 31 авг. 2022 г., 19:07 sotolko ***@***.***>:
