### ISSUE TITLE
Instant Stop 

### ISSUE THREAD

**Issue by DqRN** [sotolko/csgo-market-sniper#17]
Stops on Start-Up, might be a URL/Float issue not sure. 
![7SuZnNuhxK](https://user-images.githubusercontent.com/105587614/232963555-9a24aa29-acf5-4aea-b454-f6d6d411b2ca.png)

**Comment by DqRN** [comment]
https://twitter.com/csgofloat/status/1648717278589112320

**Comment by Cheezy1234** [comment]
i got the same issue, I think it might have something to do with the float.
![image](https://user-images.githubusercontent.com/131748333/234198614-094c2a35-6034-4eb5-8516-da7de256ea18.png)

**Comment by DqRN** [comment]
@Cheezy1234 when did it start happening?

**Comment by Cheezy1234** [comment]
i just started using it around 24 hours ago from now and it was working then it stopped when i changed some of the settings in the config i dont know if it was price of float. 
edit - I also tried deleting it and redownloading and nothing changed.
edit 2 - i also tried on a different pc and nothing changed.
It is either the format or steam or csgofloat

**Comment by Cheezy1234** [comment]
It looks like the issue is with csgo float, not the code. Assuming the tweet is right and they blocked bots I tried adding this to fix it but I got the to many requests error on steam before i could test it (it should just make the bot seem more human, but i dont know how they are blocking bots so its hard to fix): 
def save_json_response(button):
    """Function that will save JSON into variables"""
    driver.execute_script("arguments[0].click();", button)

    max_retries = 5
    delay = random.uniform(5, 15)

    for attempt in range(1, max_retries + 1):
        try:
            popup = WebDriverWait(driver, 5).until(ec.presence_of_element_located(PageLocators.POPUP))
            href = popup.get_attribute('href')

        
            headers = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
                }
           
            time.sleep(delay)

            response = requests.get('https://api.csgofloat.com/?url=' + href)
            response.raise_for_status()
            json_response = response.json()
            json_response_name = str(json_response["iteminfo"]["full_item_name"])
            json_response_float = float(json_response["iteminfo"]["floatvalue"])
            json_response_pattern = int(json_response["iteminfo"]["paintseed"])

            return json_response_name, json_response_float, json_response_pattern, json_response

        except TimeoutException:
            sys.stderr.write("Waiting too long to open item link.")
            return None

        except NoSuchElementException:
            sys.stderr.write("Can't open item link")
            return None

        except requests.exceptions.HTTPError as e:
            if e.response.status_code == 429:
                print(f"Rate limit exceeded. Retrying in {delay} seconds... (attempt {attempt})")
                delay *= 2  # Increase the delay for the next attempt
            else:
                raise e

    print(f"Failed to get JSON response after {max_retries} attempts.")
    return None

**Comment by DqRN** [comment]
@Cheezy1234 

Thank for looking into it, from what I've seen it is failing to get data when it inspects the individual listings. You might notice if you keep rerunning the script over and over after it crashs, sometime it manages to inspects a few listing before crashing, rather then the normal crash at the first listing inspection. That said, it must be an csfloat API issue

Do you reckon it's possible too pull float and pattern data from steam itself rather then csgofloat?

**Comment by Cheezy1234** [comment]
i dont think its possible to get it directly from steam. When I tested the code I added I get rate limited so i think we just need to wait for csfloat to fix itself or for the bot developer to help out.
![image](https://user-images.githubusercontent.com/131748333/234484499-cf5abf64-b1be-4d4a-80c1-2db3bf697082.png)

**Comment by DqRN** [comment]
Crazy idea, can the floatdb chrome extension be added to the chrome instance and get the script to fetch the displayed float and patterns. Thus, eliminating the need pull from the api and if there is an API error it will ignore it and continue. Oooor... Here me out we wait for float db to fix itself.
