### ISSUE TITLE
There is a problem when starting the program, what could be the problem?

### ISSUE THREAD

**Issue by kudaevE** [sotolko/csgo-market-sniper#2]
Threw a screenshot error
![image](https://user-images.githubusercontent.com/101454867/187669704-e4656f27-57ca-4c63-a882-628ff768c915.png)

**Comment by sotolko** [comment]
I am trying to replicate this error, and my friend also tried to but it works fine. Do you have latest version of Selenium installed?

**Comment by kudaevE** [comment]
now I'll try to reinstall windows, most likely errors because of this, because there are too many errors

**Comment by sotolko** [comment]
Tell me when you reinstall and tried again. If this error still shows, tell me version of your python,version of all dependencies and version of your browser please.

**Comment by kudaevE** [comment]
The error has been fixed, thank you very much, I would like to know your Telegram account if you have one, and ask you questions there and give any suggestions about the project.

**Comment by sotolko** [comment]
You can check your instagram.

**Comment by kudaevE** [comment]
I have requested from you, access is closed
