### ISSUE TITLE
Very interesting question

### ISSUE THREAD

**Issue by kudaevE** [sotolko/csgo-market-sniper#3]
I can not specify the allowable float and pattern, but specify that there are 4 stickers and the maximum price, will he buy only these parameters?

**Comment by kudaevE** [comment]
And another question, and if the account is in rubles, what data should be indicated in the program? Dollars or Rubles?

**Comment by sotolko** [comment]
If you dont specify float or pattern, it should look for any. So yes, he will buy only parameters that are set by you. You need to put price in your steam market currency. so in your case rubles.
